export type InvoiceStatus = "MATCH" | "MISMATCH" | "FAILED";

export interface InvoiceRecord {
    id: string;
    invoiceNumber: string;
    customerName: string;
    invoiceDate: string;
    amount: number;
    status: InvoiceStatus;
    remarks: string;
}

export const invoiceRows: InvoiceRecord[] = [
    {
        id: "inv-001",
        invoiceNumber: "INV-001",
        customerName: "Amazon India Pvt. Ltd.",
        invoiceDate: "01 Jul 2024",
        amount: 12450,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-002",
        invoiceNumber: "INV-002",
        customerName: "Flipkart Internet Pvt. Ltd.",
        invoiceDate: "01 Jul 2024",
        amount: 8900,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-003",
        invoiceNumber: "INV-003",
        customerName: "Meesho Pvt. Ltd.",
        invoiceDate: "02 Jul 2024",
        amount: 5600,
        status: "MISMATCH",
        remarks: "GSTIN mismatch",
    },
    {
        id: "inv-004",
        invoiceNumber: "INV-004",
        customerName: "Reliance Retail Ltd.",
        invoiceDate: "03 Jul 2024",
        amount: 15200,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-005",
        invoiceNumber: "INV-005",
        customerName: "Tata Digital Ltd.",
        invoiceDate: "04 Jul 2024",
        amount: 9750,
        status: "FAILED",
        remarks: "Invalid amount",
    },
    {
        id: "inv-006",
        invoiceNumber: "INV-006",
        customerName: "Nykaa Fashion Pvt. Ltd.",
        invoiceDate: "05 Jul 2024",
        amount: 13240,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-007",
        invoiceNumber: "INV-007",
        customerName: "Myntra Designs Pvt. Ltd.",
        invoiceDate: "06 Jul 2024",
        amount: 7480,
        status: "MISMATCH",
        remarks: "PO number mismatch",
    },
    {
        id: "inv-008",
        invoiceNumber: "INV-008",
        customerName: "Dmart India Ltd.",
        invoiceDate: "07 Jul 2024",
        amount: 17650,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-009",
        invoiceNumber: "INV-009",
        customerName: "Zomato Media Pvt. Ltd.",
        invoiceDate: "08 Jul 2024",
        amount: 10420,
        status: "FAILED",
        remarks: "Missing tax breakdown",
    },
    {
        id: "inv-010",
        invoiceNumber: "INV-010",
        customerName: "Swiggy Delivery Pvt. Ltd.",
        invoiceDate: "09 Jul 2024",
        amount: 6850,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-011",
        invoiceNumber: "INV-011",
        customerName: "BigBasket Ltd.",
        invoiceDate: "10 Jul 2024",
        amount: 11890,
        status: "MISMATCH",
        remarks: "Address mismatch",
    },
    {
        id: "inv-012",
        invoiceNumber: "INV-012",
        customerName: "OYO Rooms Pvt. Ltd.",
        invoiceDate: "11 Jul 2024",
        amount: 14320,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-013",
        invoiceNumber: "INV-013",
        customerName: "Paytm Payments Pvt. Ltd.",
        invoiceDate: "12 Jul 2024",
        amount: 9210,
        status: "FAILED",
        remarks: "Duplicate invoice",
    },
    {
        id: "inv-014",
        invoiceNumber: "INV-014",
        customerName: "Croma India Pvt. Ltd.",
        invoiceDate: "13 Jul 2024",
        amount: 13110,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-015",
        invoiceNumber: "INV-015",
        customerName: "Jio Platforms Ltd.",
        invoiceDate: "14 Jul 2024",
        amount: 16450,
        status: "MISMATCH",
        remarks: "Tax rate mismatch",
    },
    {
        id: "inv-016",
        invoiceNumber: "INV-016",
        customerName: "Airtel Digital Ltd.",
        invoiceDate: "15 Jul 2024",
        amount: 11240,
        status: "MATCH",
        remarks: "-",
    },
    {
        id: "inv-017",
        invoiceNumber: "INV-017",
        customerName: "Urban Company Pvt. Ltd.",
        invoiceDate: "16 Jul 2024",
        amount: 9810,
        status: "FAILED",
        remarks: "Missing HSN code",
    },
    {
        id: "inv-018",
        invoiceNumber: "INV-018",
        customerName: "BharatPe Pvt. Ltd.",
        invoiceDate: "17 Jul 2024",
        amount: 15640,
        status: "MATCH",
        remarks: "-",
    },
];
